import PDFDocument from 'pdfkit';
import { Writable } from 'stream';

export interface PdfQuestion {
  order: number;
  text: string;
  type: 'MCQ' | 'SUBJECTIVE';
  options?: { id: string; text: string }[] | null;
  correctKey?: string | null;
}

export interface PaperPdfData {
  examTitle: string;
  setLabel: string;
  instructions?: string | null;
  durationMinutes: number;
  examDate: Date;
  generatedAt: Date;
  generatedByName: string;
  totalWeight: number;
  showAnswers?: boolean;
  questions: PdfQuestion[];
}

/**
 * Renders a printable question paper PDF for a single set, including the
 * instructions section and the anti-leak audit stamp.
 */
export function buildPaperPdf(data: PaperPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    const sink = new Writable({
      write(chunk, _enc, cb) {
        chunks.push(chunk as Buffer);
        cb();
      },
    });
    sink.on('finish', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.pipe(sink);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('Exam Shield', { align: 'center' });
    doc.moveDown(0.2);
    doc.fontSize(15).text(data.examTitle, { align: 'center' });
    doc.moveDown(0.2);
    doc.fontSize(13).font('Helvetica').text(data.setLabel, { align: 'center' });
    doc.moveDown(0.5);
    doc
      .fontSize(10)
      .text(
        `Exam Date: ${data.examDate.toDateString()}    Duration: ${data.durationMinutes} minutes`,
        { align: 'center' },
      );
    doc.moveDown(0.8);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.6);

    // Instructions
    doc.fontSize(12).font('Helvetica-Bold').text('Instructions');
    doc.moveDown(0.2);
    doc.fontSize(10).font('Helvetica');
    const instructions =
      data.instructions ??
      'Read all questions carefully. Attempt all questions. For MCQs, select the single best option. No electronic devices are permitted. Any malpractice will lead to disqualification.';
    instructions.split('\n').forEach((line) => doc.text(`• ${line.trim()}`));
    doc.moveDown(0.8);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.6);

    // Questions or answer key
    doc.fontSize(12).font('Helvetica-Bold').text('Questions');
    doc.moveDown(0.4);
    data.questions.forEach((q) => {
      doc.fontSize(11).font('Helvetica-Bold').text(`Q${q.order}. `, { continued: true });
      doc.font('Helvetica').text(q.text);
      if (q.type === 'MCQ' && q.options) {
        doc.moveDown(0.1);
        if (data.showAnswers) {
          const chosen = q.options.find((opt) => opt.id === q.correctKey);
          doc.fontSize(10).fillColor('#1f1720').text(`    Answer key: ${chosen ? chosen.text : 'N/A'}`);
        } else {
          q.options.forEach((opt, i) => {
            const letter = String.fromCharCode(65 + i);
            doc.fontSize(10).text(`    (${letter}) ${opt.text}`);
          });
        }
      } else {
        doc.moveDown(1.5);
      }
      doc.moveDown(0.4);
    });

    // Audit stamp footer (anti-leak)
    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.3);
    doc.fontSize(8).font('Helvetica-Oblique').fillColor('#555');
    doc.text(`Set difficulty weight: ${data.totalWeight}`);
    doc.text(`Generated at: ${data.generatedAt.toISOString()}`);
    doc.text(`Generated by: ${data.generatedByName}`);
    doc.text(`For exam dated: ${data.examDate.toISOString()}`);
    doc.text('Confidential — anti-leak audit record embedded by Exam Shield.');

    doc.end();
  });
}
